
input("voce gosta de chupar caceta?(SIM/NÃO)")
'SIM'
print("bleeeh")
...       
SyntaxError: unterminated string literal (detected at line 1)
>>> print("bleeeeh")
...       
bleeeeh
>>> total_dinheiros='total de moners é 200'
...       
>>> print(total_dinheiros)
...       
total de moners é 200
>>> quantidade='90'
...       
>>> print(quantidade,'de moners voce tem')
...       
90 de moners voce tem
>>> VARIAVEL_BOLADA='muito bolada mesmo'
...       
>>> print(VARIAVEL_BOLADA)
...       
muito bolada mesmo
